name = "Create: Quality Not Assured"
author = "Sythiex"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "546a944fe397bc0f034c996322624db05180e12547dda5a02c9055905e3c4f69"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
