name = "Create: Quality Not Assured"
author = "Sythiex"
version = "1.0.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b0e8e8208450a441ef684f0841edfa2bfd4af47f360fb689105e9f80ca866fb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
