name = "Create: Quality Not Assured"
author = "Sythiex"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78126afa0e78ad88c140c2eb522e8181876758a5d290f4ba408f28304da2b74b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
