version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEPTH"
leavesCullingAmount = 1
includeMangroveRoots = true
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
music_disc_maker = true
mcwfences = true
farmersdelight = true
cookingforblockheads = true
simplemagnets = true
create_aeronautics_placeable_wheels = true
coastersmagnetized = true
createcafe = true
simulatedcoasters = true
mcwstairs = true
chimes = true
colorfulazaleas = true
easyanvils = true
copycats = true
comforts = true
modulardynamics = true
railways = true
mcwbridges = true
tinyredstone = true
hole_filler_mod = true
bits_n_bobs = true
mynethersdelight = true
handcrafted = true
ftbquests = true
functionalstorage = true
snowrealmagic = true
create_radar = true
drill_drain = true
exposure = true
offroad = true
tinymultiblocklib = true
naturalist = true
supplementaries = true
cccbridge = true
endersdelight = true
pretty_in_pink = true
createbigcannons = true
aeronautics_delivery_quests = true
createprism = true
moderntrainparts = true
create_confectionery = true
createrailwaysnavigator = true
petrolpark = true
culturaldelights = true
create = true
yungscavebiomes = true
create_aeronautics_toolgun = true
glassential = true
advancedperipherals = true
cluttered = true
createoreexcavation = true
visualworkbench = true
minecraft = true
create_connected = true
cocktailsdelight = true
rusticdelight = true
azimuth = true
starcatcher = true
mcwfurnitures = true
travelersbackpack = true
dragonlib = true
cookscollection = true
createframed = true
additional_lights = true
create_bb = true
petrolsparts = true
create_aquatic_ambitions = true
aeroworks = true
create_power_loader = true
luminax = true
streamsreflowing = true
framedblocks = true
mcwroofs = true
mcwwindows = true
createpropulsion = true
createcoasterseats = true
oceansdelight = true
easymagic = true
brewinandchewin = true
connectedglass = true
betterend = true
quark = true
another_furniture = true
doubleslabs = true
redomesticate = true
diagonalwalls = true
selling_bin = true
create_enchantment_industry = true
mcwpaths = true
ccterminals = true
aeroclaims = true
simplylight = true
tinygates = true
aeronautics_utility_objects = true
fastpaintings = true
escalated = true
mcwtrpdoors = true
mcwlights = true
bellsandwhistles = true
cbc_at = true
amendments = true
create_aero_radar = true
mcwholidays = true
diagonalfences = true
moonlight = true
exposure_space = true
create_tweaked_controllers = true
farmerspizzeria = true
ags_modernmarkings = true
balancedflight = true
mcwdoors = true
create_hypertube = true
factory_blocks = true
create_factory = true
cloudglass = true
nomowanderer = true
chipped = true
tfmg = true
aeronautics = true
interiors = true
simulated = true
createvoidtank = true
struts = true
fairylights = true
displaydelight = true
create_dragons_plus = true
lootr = true
createdeco = true
create_bic_bit = true
ratatouille = true
ccpe = true
beautify = true
ccrj45 = true
crabbersdelight = true
diagonalwindows = true
computercraft = true
create_chipped = true
create_integrated_farming = true
