[milestones]
	#Number of hearts you start out with.
	# Default: 10
	# Range: 0 ~ 1000
	baseHearts = 10
	#Number of hearts you gain for reaching a new milestone.
	# Default: 2
	# Range: 0 ~ 1000
	heartsPerMilestone = 1
	#A list of numbers of unique foods you need to eat to unlock each milestone, in ascending order. Naturally, adding more milestones lets you earn more hearts.
	milestones = [30, 70, 120, 180, 250, 330, 420, 540, 700, 875]

[filtering]
	#Foods in this list won't affect the player's health nor show up in the food book.
	blacklist = [
	    "armamentarium:ambrosia",
	    "armamentarium:coagulated_netherblood",
	    "armamentarium:rum_coconut",
	    "armamentarium:rum_lime",
	    "armamentarium:rum_orange",
	    "armamentarium:rum_passion",
	    "armamentarium:rum_pineapple",
	    "armamentarium:rum_strawberry",
	    "armamentarium:sacramental_grape_remains",
	    "armamentarium:the_mind_of_jean",
	    "crabbersdelight:raw_squid_tentacles",
	    "crabbersdelight:raw_glow_squid_tentacles",
	    "crabbersdelight:cooked_squid_tentacles",
	    "crabbersdelight:cooked_glow_squid_tentacles",
	    "oceansdelight:tentacles",
	    "rusticdelight:calamari",
	    "rusticdelight:calamari_slice",
	    "rusticdelight:cooked_calamari",
	    "rusticdelight:calamari_roll",
	    "createcafe:aloe_milk_tea",
	    "createcafe:apricot_milk_tea",
	    "createcafe:banana_iced_coffee",
	    "createcafe:banana_milk_tea",
	    "createcafe:barberry_milk_tea",
	    "createcafe:blackberry_milk_tea",
	    "createcafe:blood_orange",
	    "createcafe:blood_orange_milk_tea",
	    "createcafe:blueberry_milk_tea",
	    "createcafe:cherry_milk_tea",
	    "createcafe:citron_milk_tea",
	    "createcafe:dragonfruit_milk_tea",
	    "createcafe:durian_milk_tea",
	    "createcafe:fig_milk_tea",
	    "createcafe:gooseberry_milk_tea",
	    "createcafe:grapefruit_milk_tea",
	    "createcafe:guava_milk_tea",
	    "createcafe:jackfruit_milk_tea",
	    "createcafe:kiwi_milk_tea",
	    "createcafe:lavender_milk_tea",
	    "createcafe:lime_milk_tea",
	    "createcafe:lychee_milk_tea",
	    "createcafe:mana_berries",
	    "createcafe:mana_berry_milk_tea",
	    "createcafe:mandarin_milk_tea",
	    "createcafe:mango_milk_tea",
	    "createcafe:orange_milk_tea",
	    "createcafe:papaya_milk_tea",
	    "createcafe:passionfruit_milk_tea",
	    "createcafe:persimmon_milk_tea",
	    "createcafe:pineapple_milk_tea",
	    "createcafe:plum_milk_tea",
	    "createcafe:pomegranate_milk_tea",
	    "createcafe:pomelo_milk_tea",
	    "createcafe:raspberry_iced_coffee",
	    "createcafe:raspberry_milk_tea",
	    "createcafe:redlove_milk_tea",
	    "createcafe:starfruit_milk_tea",
	    "createcafe:strawberry_iced_coffee",
	    "createcafe:strawberry_milk_tea",
	    "createcafe:tamarind_milk_tea",
	    "createcafe:vanilla_iced_coffee",
	    "createcafe:vanilla_milk_tea",
	    "createcafe:yucca_milk_tea",
	    "cocktailsdelight:aqua_velva",
	    "cocktailsdelight:blue_curacao",
	    "cocktailsdelight:brass_monkey",
	    "cocktailsdelight:china_blue",
	    "cocktailsdelight:cranberry_juice",
	    "cocktailsdelight:gimlet",
	    "cocktailsdelight:johnny_silverhand",
	    "cocktailsdelight:lemon_lime",
	    "cocktailsdelight:margarita",
	    "cocktailsdelight:medina",
	    "cocktailsdelight:mermaid_lemonade",
	    "cocktailsdelight:mojito",
	    "cocktailsdelight:nut_brown_ale",
	    "cocktailsdelight:pina_colada",
	    "cocktailsdelight:plum_wine",
	    "cocktailsdelight:salted_margarita",
	    "cocktailsdelight:screwdriver",
	    "cocktailsdelight:singapore_sling",
	    "cocktailsdelight:tequila_sunrise",
        "exposure_space:cosmic_leftover"
	]
	#When this list contains anything, the blacklist is ignored and instead only foods from here count.
	whitelist = []
	#The minimum hunger value foods need to provide in order to count for milestones, in half drumsticks.
	# Default: 1
	# Range: 0 ~ 1000
	minimumFoodValue = 1

[miscellaneous]
	#Whether or not to reset the food list on death, effectively losing all bonus hearts.
	resetOnDeath = false
	#If true, eating foods outside of survival mode (e.g. creative/adventure) is not tracked and thus does not contribute towards progression.
	limitProgressionToSurvival = false
